default_context:
  project_name: 'isonomial'
  project_slug: 'isonomial'
  domain_main: 'isonomial.com'
  domain_staging: 'stag.isonomial.com'
  docker_swarm_stack_name_main: 'isonomial-com'
  docker_swarm_stack_name_staging: 'stag-isonomial-com'
  secret_key: '730810d29510ad575a0e697cd9e73391a7136b3ca662f785aadab2b64357a9b8'
  first_superuser: 'admin@isonomial.com'
  first_superuser_password: 'aabe2754b622973aec7200a45bd5baf4db462745a1393cad2109f091fd87ebfc'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.isonomial.com", "https://stag.isonomial.com", "https://isonomial.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@isonomial.com'
  postgres_password: 'de105710629b754cb2344a19be062abf34eb270ea33927d078d04fcd21d84ecd'
  pgadmin_default_user: 'admin@isonomial.com'
  pgadmin_default_user_password: 'aabe2754b622973aec7200a45bd5baf4db462745a1393cad2109f091fd87ebfc'
  traefik_constraint_tag: 'isonomial.com'
  traefik_constraint_tag_staging: 'stag.isonomial.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:aabe2754b622973aec7200a45bd5baf4db462745a1393cad2109f091fd87ebfc'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
