"""added postvote model

Revision ID: 116490d2545c
Revises: d73b40264cc7
Create Date: 2020-07-07 19:06:53.858605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116490d2545c'
down_revision = 'd73b40264cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_uc')
    )
    op.create_index(op.f('ix_postvote_id'), 'postvote', ['id'], unique=False)
    op.create_index(op.f('ix_postvote_post_id'), 'postvote', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postvote_post_id'), table_name='postvote')
    op.drop_index(op.f('ix_postvote_id'), table_name='postvote')
    op.drop_table('postvote')
    # ### end Alembic commands ###
